// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportBroker.Infrastructure.Data;

#nullable disable

namespace ReportBroker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329140835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportBroker.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<double?>("ConversionRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("conversion_ratio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("PaymentCount")
                        .HasColumnType("integer")
                        .HasColumnName("payment_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("ReportBroker.Domain.Entities.ReportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("RequestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("report_requests", (string)null);
                });

            modelBuilder.Entity("ReportBroker.Domain.Entities.Report", b =>
                {
                    b.OwnsOne("ReportBroker.Domain.ValueObjects.ReportParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DesignId")
                                .HasColumnType("uuid")
                                .HasColumnName("design_id");

                            b1.Property<DateOnly>("PeriodEnd")
                                .HasColumnType("date")
                                .HasColumnName("period_end");

                            b1.Property<DateOnly>("PeriodStart")
                                .HasColumnType("date")
                                .HasColumnName("period_start");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("ReportId");

                            b1.HasIndex("ProductId", "DesignId", "PeriodStart", "PeriodEnd")
                                .IsUnique()
                                .HasDatabaseName("ix_reports_unique_parameters");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();
                });

            modelBuilder.Entity("ReportBroker.Domain.Entities.ReportRequest", b =>
                {
                    b.HasOne("ReportBroker.Domain.Entities.Report", "Report")
                        .WithMany("Requests")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportBroker.Domain.Entities.Report", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
